sudo: false
language: node_js
node_js:
  - 12.16.1 # use nodejs v12 LTS
cache: npm
branches:
  only:
    - develop # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: develop
  local-dir: public